name: Build
on:
  pull_request:
  push:
    branches: main
jobs:
  build:
    if: ${{ ! startsWith(github.ref, 'refs/tags/') }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Just
      uses: extractions/setup-just@v3
    - name: Go
      uses: actions/setup-go@v5
    - name: Build
      run: just build
